#!/usr/bin/env node
'use strict';

/**
 * Download the Google Fonts used by AnyOSStack and rewrite the CSS to point at
 * local .woff2 files, so the packaged desktop app renders correctly fully
 * offline (no runtime request to fonts.googleapis.com / fonts.gstatic.com).
 *
 * Only the `latin` and `latin-ext` subsets are bundled: the three families
 * (Playfair Display, Hanken Grotesk, Spline Sans Mono) are UI/display faces
 * that do not carry CJK/Arabic glyphs anyway, so non-latin content already
 * falls back to the host system fonts exactly as it did with the CDN.
 *
 * Run from the repo root:  node scripts/fetch-fonts.js
 * Requires the CSS already fetched at
 * src/renderer/assets/fonts/google-fonts.css (or pass --refetch).
 *
 * Port of the original scripts/fetch-fonts.py.
 */

const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const FONTS_DIR = path.resolve(HERE, '..', 'src', 'renderer', 'assets', 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2?'
  + 'family=Playfair+Display:wght@600;700;800&'
  + 'family=Hanken+Grotesk:wght@400;500;600;700;800&'
  + 'family=Spline+Sans+Mono:wght@400;500;600&display=swap';
// Google serves woff2 only to browsers it recognises; keep the desktop UA.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILY_SLUG = {
  'Playfair Display': 'playfair-display',
  'Hanken Grotesk': 'hanken-grotesk',
  'Spline Sans Mono': 'spline-sans-mono',
};

async function httpGet(url, binary = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return binary ? Buffer.from(await res.arrayBuffer()) : await res.text();
}

async function main() {
  fs.mkdirSync(FONTS_DIR, { recursive: true });
  const cssPath = path.join(FONTS_DIR, 'google-fonts.css');
  if (process.argv.includes('--refetch') || !fs.existsSync(cssPath)) {
    console.log('Fetching CSS...');
    fs.writeFileSync(cssPath, await httpGet(CSS_URL), 'utf8');
  }

  const css = fs.readFileSync(cssPath, 'utf8');

  // Split into blocks keyed by the /* subset */ comment that precedes each
  // @font-face. parts = ['', subset1, block1, subset2, block2, ...]
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//);
  const outBlocks = [];
  const seen = new Set();

  for (let i = 1; i < parts.length; i += 2) {
    const subset = parts[i].trim();
    const block = parts[i + 1];
    if (!KEEP_SUBSETS.has(subset)) continue;

    const fam = /font-family:\s*'([^']+)'/.exec(block);
    const weight = /font-weight:\s*(\d+)/.exec(block);
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block);
    if (!(fam && weight && url)) continue;

    const slug = FAMILY_SLUG[fam[1]];
    if (!slug) continue;

    const fname = `${slug}-${weight[1]}-${subset}.woff2`;
    const famDir = path.join(FONTS_DIR, slug);
    fs.mkdirSync(famDir, { recursive: true });
    const dest = path.join(famDir, fname);

    if (!seen.has(fname)) {
      console.log(`  ${fname}`);
      fs.writeFileSync(dest, await httpGet(url[1], true));
      seen.add(fname);
    }

    let localBlock = block.replace(url[0], `url(./${slug}/${fname}) format('woff2')`);
    // strip any leftover format() duplicate
    localBlock = localBlock.replace(/format\('woff2'\)\s*format\('woff2'\)/g, "format('woff2')");
    outBlocks.push(`/* ${subset} */${localBlock}`);
  }

  const header = '/* AnyOSStack bundled fonts - generated by scripts/fetch-fonts.js.\n'
    + '   Local latin/latin-ext subsets of Playfair Display, Hanken Grotesk,\n'
    + '   and Spline Sans Mono, so the app renders offline with no CDN call. */\n';
  fs.writeFileSync(path.join(FONTS_DIR, 'fonts.css'), header + outBlocks.join(''), 'utf8');
  console.log(`Wrote ${outBlocks.length} @font-face rules to fonts.css`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
