#!/usr/bin/env sh
# AnyOSStack bootstrap - macOS / Linux / any POSIX shell (incl. Git Bash, WSL)
#
#     curl -fsSL https://raw.githubusercontent.com/tweedlex754/AnyOSStack/main/scripts/bootstrap/get.sh | sh
#
# Downloads the package for your platform and leaves it on your Desktop.
# No sudo is needed to download.
#
# On macOS and Linux this fetches that platform's own package (.dmg / .AppImage)
# from the latest Release. Elsewhere - or with ANYOSSTACK_ARTIFACT=windows - it
# rebuilds the Windows installer, which is useful when you are preparing a
# Windows machine from a Mac.
#
# The Windows installer has two sources, in order:
#   1. the Release asset - one file, the normal path
#   2. the chunked copy in the repository - only if the Release is unreachable
# Every download is checked against the SHA-256 in the manifest, and the
# rejoined file is checked again as a whole.

set -eu

REPO="${ANYOSSTACK_REPO:-tweedlex754/AnyOSStack}"
BASE="${ANYOSSTACK_BASE:-https://raw.githubusercontent.com/${REPO}/main/installer-parts}"

say()  { printf '  %s\n' "$1"; }
die()  { printf '  error: %s\n' "$1" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed"; }
need curl

# sha256 tool differs across platforms; pick whichever exists.
if command -v sha256sum >/dev/null 2>&1; then
  sha_of() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
  sha_of() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  die "need sha256sum or shasum to verify downloads"
fi

# Minimal JSON field readers. The manifest is generated by
# scripts/split-installer.js and is flat and predictable, so this avoids making
# python/jq a requirement just to read four values.
json_str() { sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -n1; }
json_num() { sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' "$1" | head -n1; }

desktop_dir() {
  if [ -d "$HOME/Desktop" ]; then printf '%s' "$HOME/Desktop"
  elif command -v xdg-user-dir >/dev/null 2>&1 && [ -d "$(xdg-user-dir DESKTOP 2>/dev/null)" ]; then
    xdg-user-dir DESKTOP
  else printf '%s' "$HOME"
  fi
}

OS="$(uname -s 2>/dev/null || echo unknown)"
WANT="${ANYOSSTACK_ARTIFACT:-auto}"
if [ "$WANT" = auto ]; then
  case "$OS" in
    Darwin) WANT=macos ;;
    Linux)  WANT=linux ;;
    *)      WANT=windows ;;
  esac
fi

DEST="$(desktop_dir)"
TMP="$(mktemp -d 2>/dev/null || mktemp -d -t anyosstack)"
trap 'rm -rf "$TMP"' EXIT INT TERM

printf '\nAnyOSStack installer bootstrap\n\n'

# --- macOS / Linux: take the native package straight from the Release --------
if [ "$WANT" = macos ] || [ "$WANT" = linux ]; then
  case "$WANT" in
    macos) PATTERN='\.dmg' ;;
    linux) PATTERN='\.AppImage' ;;
  esac
  say "looking for the latest $WANT package"
  API="https://api.github.com/repos/${REPO}/releases/latest"
  if ! curl -fsSL -H 'User-Agent: anyosstack-bootstrap' "$API" -o "$TMP/rel.json"; then
    die "no published release yet for ${REPO} - build from source, or run with ANYOSSTACK_ARTIFACT=windows"
  fi
  URL="$(tr ',' '\n' < "$TMP/rel.json" | sed -n 's/.*"browser_download_url"[[:space:]]*:[[:space:]]*"\([^"]*'"$PATTERN"'\)".*/\1/p' | head -n1)"
  [ -n "$URL" ] || die "the latest release has no $WANT package attached"
  FILE="$(basename "$URL")"
  say "downloading $FILE"
  curl -fL --progress-bar -H 'User-Agent: anyosstack-bootstrap' "$URL" -o "$TMP/$FILE"
  mv -f "$TMP/$FILE" "$DEST/$FILE"
  printf '\n  saved to %s\n\n' "$DEST/$FILE"
  [ "$WANT" = linux ] && say "make it executable:  chmod +x \"$DEST/$FILE\""
  exit 0
fi

# --- Windows installer: release asset first, chunks as fallback --------------
say "reading manifest"
curl -fsSL -H 'User-Agent: anyosstack-bootstrap' "$BASE/manifest.json" -o "$TMP/manifest.json" \
  || die "cannot reach $BASE/manifest.json"

NAME="$(json_str "$TMP/manifest.json" artifact)"
SHA="$(json_str "$TMP/manifest.json" sha256)"
VERSION="$(json_str "$TMP/manifest.json" version)"
TOTAL="$(json_num "$TMP/manifest.json" totalSize)"
COUNT="$(json_num "$TMP/manifest.json" partCount)"
RELURL="$(json_str "$TMP/manifest.json" releaseAssetUrl)"
[ -n "$NAME" ] && [ -n "$SHA" ] || die "manifest is missing artifact/sha256"
say "AnyOSStack ${VERSION} - $((TOTAL / 1048576)) MB"

TARGET="$DEST/$NAME"
if [ -f "$TARGET" ] && [ "$(sha_of "$TARGET")" = "$SHA" ]; then
  say "already on your Desktop and verified: $TARGET"
  exit 0
fi

STAGED="$TMP/$NAME"
GOT=0
if [ -n "$RELURL" ]; then
  say "trying the release asset"
  if curl -fL --progress-bar -H 'User-Agent: anyosstack-bootstrap' "$RELURL" -o "$STAGED" 2>/dev/null \
     && [ "$(sha_of "$STAGED")" = "$SHA" ]; then
    GOT=1
    say "downloaded in one piece"
  else
    say "no usable release asset - falling back to the chunked copy"
    rm -f "$STAGED"
  fi
fi

if [ "$GOT" -eq 0 ]; then
  say "downloading ${COUNT} parts"
  : > "$STAGED"
  # Part names and their checksums, paired line by line, straight from the JSON.
  # The manifest is pretty-printed, so each part object spans several lines and
  # sed - which works a line at a time - would never see name and sha256
  # together. Strip the newlines first, then split on '{' so one part lands on
  # one line.
  tr -d '\r\n' < "$TMP/manifest.json" | tr '{' '\n' \
    | sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\.part[0-9]*\)".*"sha256"[[:space:]]*:[[:space:]]*"\([0-9a-f]*\)".*/\1 \2/p' \
    > "$TMP/parts.txt"
  [ -s "$TMP/parts.txt" ] || die "could not read the part list from the manifest"
  N=0
  # `|| [ -n "$PNAME" ]` is load-bearing: stripping the newlines above leaves the
  # final part without a terminator, and a bare `read` discards an unterminated
  # last line - which silently dropped the last chunk.
  while read -r PNAME PSHA || [ -n "$PNAME" ]; do
    N=$((N + 1))
    curl -fsSL -H 'User-Agent: anyosstack-bootstrap' "$BASE/$PNAME" -o "$TMP/$PNAME" \
      || die "failed to download $PNAME"
    [ "$(sha_of "$TMP/$PNAME")" = "$PSHA" ] || die "part $PNAME failed its checksum"
    # Assembled as the parts arrive, not after: each chunk is verified, appended
    # to the single output file, then deleted. You never end up holding a pile
    # of .part files to merge yourself.
    cat "$TMP/$PNAME" >> "$STAGED"
    rm -f "$TMP/$PNAME"
    DONE=$(wc -c < "$STAGED" | tr -d ' ')
    printf '    %s/%s  assembled %s / %s MB\n' "$N" "$COUNT" \
      "$((DONE / 1048576))" "$((TOTAL / 1048576))"
  done < "$TMP/parts.txt"
fi

say "verifying"
[ "$(sha_of "$STAGED")" = "$SHA" ] || die "the rejoined file does not match the published checksum"
say "checksum matches"

mv -f "$STAGED" "$TARGET"
printf '\n  saved to %s\n\n' "$TARGET"
case "$OS" in
  MINGW*|MSYS*|CYGWIN*) say "run it:  \"$TARGET\"" ;;
  *) say "this is the Windows installer - copy it to a Windows machine to run it." ;;
esac
printf '\n'
